Apps 521 sinai add fields to pulldown on search bar2
UCLALibrary/ursus pull request #931
Opened 2020-12-04 02:42 UTC by darrowcoucla

2020-12-04 16:27 UTC, pghorpade commented on app/controllers/catalog_controller.rb
> +        field.solr_parameters = {
Add a label: 'Shelfmark'

2020-12-04 16:30 UTC, pghorpade requested changes
Also add a cypress test for sinai search with search fields.

2020-12-07 18:50 UTC, darrowcoucla commented on app/controllers/catalog_controller.rb
> +        field.solr_parameters = {
Updated

2020-12-07 18:54 UTC, pghorpade approved these changes

2020-12-07 18:56 UTC, merged