APPS-597_Sinai-index-changes
UCLALibrary/ursus pull request #968
Opened 2021-02-04 19:07 UTC by jendiamond

2021-02-11 22:17 UTC, aprigge requested changes
@jendiamond, one change can you remove the limit:7 in the catalog controller for the sinai facets. Has to be removed for the scrolling facets.

2021-02-11 22:21 UTC, aprigge commented on app/controllers/catalog_controller.rb
> +      config.add_facet_field 'genre_sim', sort: 'index', limit: 7
Remove the limit:7 for Sinai facets.

2021-02-12 00:04 UTC, pghorpade approved these changes
👍

2021-02-12 00:07 UTC, aprigge approved these changes

2021-02-12 00:08 UTC, merged